remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: pattersonmftcc's homepage
description: GitHub Pages example for promoting a project.


